name: analytic
description: |
  Analytic Workbench system zookeeper
version: 0.1.0-rancher1
category: Clustering
maintainer: "Renato Mendes rmendes@scipionyx.io"
license: 
projectURL: http://www.scipionyx.io
